# kubernetes/overlays/gke/patch-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capoc
  namespace: ns-lcl
spec:
  template:
    spec:
      containers:
      - name: capoc
        env:
        - name: CLOUD_PROVIDER
          value: "gcp-gke"